language: bash
sudo: required
services:
  - docker
git:
  depth: 1
  submodules: false
branches:
  only:
  - master
before_install:
  - docker run --volume ${PWD}/:/app/ node:9.3.0-alpine bash -c 'cd /app/; npm run lint;'
  - sudo apt-get update -qq
install: true
before_script:
script:
before_cache:
after_success:
after_failure:
before_deploy:
deploy:
  skip_cleanup: true
after_deploy:
after_script: