language: bash
sudo: required
services:
  - docker
git:
  depth: 1
  submodules: false
branches:
  only:
  - master
before_install:
  - npm install
  - eslint ./
install:
  - npm test
before_script:
script:
before_cache:
after_success:
after_failure:
before_deploy:
deploy:
  skip_cleanup: true
after_deploy:
after_script: