version: '3'
services:
  portfolio-api:
    image: node:9.3.0-alpine
    container_name: portfolio-api
    user: node
    working_dir: /home/node/app/
    command: /bin/sh -c 'cd /home/node/app; npm install; node --inspect=0.0.0.0 ./bin/www;'
    environment:
      - PORTFOLIO_CONFIG_PASSWORD=${PORTFOLIO_CONFIG_PASSWORD}
      - PORTFOLIO_CONFIG_FILE_PATH=/home/node/app/configs-local.json
    ports:
      - "9229:9229"
      - "3000:3000"
    volumes:
      - ./:/home/node/app/
    depends_on:
      - portfolio-db-init
    links:
      - portfolio-db
  portfolio-db-init:
    image: mongo:3.6.1
    command: mongo --nodb /home/mongodb/mongo-setup.js
    container_name: portfolio-db-init
    user: mongodb
    working_dir: /home/mongodb/
    volumes:
      - ./mongo-setup.js:/home/mongodb/mongo-setup.js
    depends_on:
      - portfolio-db
    links:
      - portfolio-db
  portfolio-db:
    image: mongo:3.6.1
    command: mongod
    user: mongodb
    working_dir: /home/mongodb/
    container_name: portfolio-db
    volumes:
      - ./data/db:/data/db
      - ./mongod.conf:/etc/mongod.conf
    expose:
     - "27017"