image: jbacon47/portfolio-api:latest
imagePullPolicy: Always
imagePullSecrets:
# - name: secret-name
replicas: 2
nodeEnv: development
configSecret: portfolioapi-joshbacon-name # kube secret name holding password to baked-in config file
codeOverrideDirectory: /Users/ap5s/Development/github.com/jbacon/blog-api-server/ # This enables debug development mode
# gkeStaticExternalIpId: "techhub-ip" # This enables Ingress creation on the GKE cluster
# tlsSecret: portfolio-api-tls
# letsEncryptService: portfolioapi-joshbacon-name-cert-renewal
resources:
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  requests:
    cpu: 20m
    # memory: 128Mi