apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  {{- if .Values.gkeStaticExternalIpId }}
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.gkeStaticExternalIpId }}
  {{- end }}
spec:
  {{- if .Values.tlsSecret }}
  tls:
  - secretName: {{ .Values.tlsSecret }}
  {{- end }}
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: {{ template "fullname" . }}-api
          servicePort: 3000