apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fullname" . }}-api
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
  {{- if .Values.gkeStaticExternalIpId  }}
  # annotations:
  #   service.alpha.kubernetes.io/app-protocols: '{"my-https-port":"HTTPS"}'
  {{- end }}
spec:
  type: NodePort
  selector:
    app: {{ template "fullname" . }}-api
  ports:
    - name: api
      port: 3000
      protocol: TCP
      targetPort: 3000
    {{- if eq .Values.nodeEnv "development" }}
    - name: debug
      port: 9229
      protocol: TCP
      targetPort: 9229
    {{- end }}