---
apiVersion: v1
kind: ConfigMap
metadata:
  name: portfolio-joshbacon-name-certbot-hooks
  namespace: default
  labels:
    app: portfolio-joshbacon-name-certbot-hooks
data:
  auth.sh: |
    #!/bin/sh
    echo ${CERTBOT_VALIDATION} > ./${CERTBOT_TOKEN}
    pip install awscli
    aws s3 cp ./${CERTBOT_TOKEN} s3://portfolio.joshbacon.name/.well-known/acme-challenge/${CERTBOT_TOKEN}
    sleep 30
  cleanup.sh: |
    #!/bin/sh
    rm -f ./${CERTBOT_TOKEN}
    pip install awscli
    aws s3 rm --recursive s3://portfolio.joshbacon.name/.well-known/acme-challenge/
    wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-204.0.0-linux-x86_64.tar.gz
    echo "276984a44a2a9dc1af5d3c859a1295897fd8cfc911738874daf007ab46143da5  google-cloud-sdk-204.0.0-linux-x86_64.tar.gz" \
    | sha256sum -c -
    tar -xvf google-cloud-sdk-204.0.0-linux-x86_64.tar.gz
    ./google-cloud-sdk/install.sh --quiet
    cd ./google-cloud-sdk
    source ${PWD}/path.bash.inc
    cd ..
    gcloud components install kubectl
    kubectl create secret generic portfolio-joshbacon-name-certs \
    --from-file=cert.pem=/root/certs/cert.pem \
    --from-file=privkey.pem=/root/certs/privkey.pem \
    --from-file=fullchain.pem=/root/certs/fullchain.pem \
    --from-file=chain.pem=/root/certs/chain.pem \
    --dry-run \
    -o yaml \
    | kubectl apply -f -
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: portfolioapi-joshbacon-name-certbot-hooks
  namespace: default
  labels:
    app: portfolioapi-joshbacon-name-certbot-hooks
data:
  auth.sh: |
    #!/bin/sh
    echo ${CERTBOT_VALIDATION} > ./${CERTBOT_TOKEN}
    pip install awscli
    aws s3 cp ./${CERTBOT_TOKEN} s3://portfolio.joshbacon.name/.well-known/acme-challenge/${CERTBOT_TOKEN}
    sleep 30
  cleanup.sh: |
    #!/bin/sh
    rm -f ./${CERTBOT_TOKEN}
    pip install awscli
    aws s3 rm --recursive s3://portfolio.joshbacon.name/.well-known/acme-challenge/
    kubectl create secret generic portfolio-joshbacon-name-certs \
    --from-file=cert.pem=/root/cert.pem \
    --from-file=privkey.pem=/root/privkey.pem \
    --from-file=fullchain.pem=/root/fullchain.pem \
    --from-file=chain.pem=/root/chain.pem \
    --dry-run \
    -o yaml \
    | kubectl apply -f -
---
apiVersion: v1
kind: Service
metadata:
  name: portfolioapi-joshbacon-name-cert-renewal
  namespace: default
  labels:
    app: portfolioapi-joshbacon-name-cert-renewal
spec:
  type: NodePort
  selector:
    app: portfolioapi-joshbacon-name-cert-renewal
  ports:
    - name: server
      port: 8888
      nodePort: 32353
      protocol: TCP
      targetPort: 8888
---
apiVersion:
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: portfolio-joshbacon-name-cert-renewal
  namespace: default
  labels:
    app: portfolio-joshbacon-name-cert-renewal
spec:
  schedule: "0 8 1 * *"
  startingDeadlineSeconds: 120
  concurrencyPolicy: Forbid
  suspend: false
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      labels:
        app: portfolio-joshbacon-name-cert-renewal
    spec:
      activeDeadlineSeconds: 600
      completions: 1
      parallelism: 1
      backoffLimit: 1
      template:
        spec:
          restartPolicy: OnFailure
          dnsPolicy: ClusterFirst
          terminationGracePeriodSeconds: 300
          serviceAccountName: portfolio-joshbacon-name-certs-renewer
          containers:
            - name: portfolio-joshbacon-name-cert-renewal
              image: certbot/certbot
              imagePullPolicy: Always
              args:
                - certonly
                - --cert-path=/root/certs/cert.pem
                - --key-path=/root/certs/privkey.pem
                - --fullchain-path=/root/certs/fullchain.pem
                - --chain-path=/root/certs/chain.pem
                - --config-dir=/root/certbot/config/
                - --work-dir=/root/certbot/work/
                - --logs-dir=/root/certbot/logs/
                - --non-interactive
                - --keep-until-expiring
                - --manual
                - --manual-auth-hook=/root/hooks/auth.sh
                - --manual-cleanup-hook=/root/hooks/cleanup.sh
                - --manual-public-ip-logging-ok
                - --agree-tos
                - --email=jbacon@zagmail.gonzaga.edu
                - --domain=portfolio.joshbacon.name
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-keys
                      key: aws_access_key_id
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-keys
                      key: aws_secret_access_key
                - name: AWS_DEFAULT_REGION
                  value: us-west-2
              volumeMounts:
                - name: certs
                  mountPath: /root/certs/
                - name: hooks
                  mountPath: /root/hooks/
              ports:
                - name: server
                  containerPort: 8888
                  protocol: TCP
          volumes:
            - name: certs
              secret:
                secretName: portfolio-joshbacon-name-certs
            - name: hooks
              configMap:
                name: portfolio-joshbacon-name-certbot-hooks
                defaultMode: 0744
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: portfolioapi-joshbacon-name-cert-renewal
  namespace: default
  labels:
    app: portfolioapi-joshbacon-name-cert-renewal
spec:
  schedule: "0 8 1 * *"
  startingDeadlineSeconds: 120
  concurrencyPolicy: Forbid
  suspend: false
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      labels:
        app: portfolioapi-joshbacon-name-cert-renewal
    spec:
      activeDeadlineSeconds: 360
      completions: 1
      parallelism: 1
      backoffLimit: 1
      template:
        spec:
          restartPolicy: OnFailure
          dnsPolicy: ClusterFirst
          terminationGracePeriodSeconds: 300
          serviceAccountName: portfolioapi-joshbacon-name-certs-renewer
          containers:
            - name: portfolioapi-joshbacon-name-cert-renewal
              image: certbot/certbot
              imagePullPolicy: Always
              args:
                - certonly
                - --cert-path=/root/certs/cert.pem
                - --key-path=/root/certs/privkey.pem
                - --fullchain-path=/root/certs/fullchain.pem
                - --chain-path=/root/certs/chain.pem
                - --config-dir=/root/certbot/config/
                - --work-dir=/root/certbot/work/
                - --logs-dir=/root/certbot/logs/
                - --non-interactive
                - --keep-until-expiring
                - --manual
                - --manual-auth-hook=/root/certs/auth.sh
                - --manual-cleanup-hook=/root/certs/cleanup.sh
                - --manual-public-ip-logging-ok
                - --agree-tos
                - --email=jbacon@zagmail.gonzaga.edu
                - --domain=portfolioapi.joshbacon.name
              volumeMounts:
                - name: certs
                  mountPath: /root/certs/
              ports:
                - name: server
                  containerPort: 8888
                  protocol: TCP
          volumes:
            - name: certs
              secret:
                secretName: portfolioapi-joshbacon-name-certs